name: Auto-merge dependabot

permissions:
  contents: write

on:
  pull_request:
    branches: 
      - main
    
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: auto merge dependabot
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}} # Detect that the PR author is dependabot
        run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
